### ISSUE TITLE
How to run project on local machine

### ISSUE THREAD

**Issue by kamranghyan123** [Bonfida/token-vesting#9]
Hi! I need assistance how to run project on local machine and as well want to customize the solution for own use.

**Comment by vikas-speqto** [comment]
Hello @kamranghyan123 did you get any solution?

**Comment by dr497** [comment]
You can run the program on your local machine using program test. It's also available on devnet https://explorer.solana.com/address/Hj9R6bEfrULLNrApMsKCEaHR9QJ2JgRtM381xgYcjFmQ?cluster=devnet

**Comment by vikas-speqto** [comment]
Hello @dr497 ,

Thank for your quick response, we are able to deploy code on devnet, we are able to create token and token account and build CLI. But the problem is we are not able to execute lock and unlock functionality.
**Below is the code which we use to execute the lock functionality** 
`Create vesting instance and store its SEED value

echo "RUST_BACKTRACE=1 ./target/debug/vesting-contract-cli                          \
--url https://devnet.solana.com                                                     \
--program_id $PROGRAM_ID                           \
create                                                                              \
--mint_address $MINT                         \
--source_owner ~/.config/solana/id_owner.json                                             \
--source_token_address $TOKEN_ACCOUNT                                             \
--destination_token_address $ACCOUNT_TOKEN_DEST                  \
--amounts 2,1,3,!                                                                   \
--release-times 1,28504431,2850600000000000,!                                             \
--payer ~/.config/solana/id_owner.json"                  \
--verbose | bash ` 

**And unlock tokens according schedule:**

```
echo "RUST_BACKTRACE=1 ./target/debug/vesting-contract-cli                          \
--url https://devnet.solana.com                                                     \
--program_id $PROGRAM_ID                           \
unlock                                                                              \
--seed $SEED                                  \
--payer ~/.config/solana/id_owner.json" | bash
```

After executing this code we are not able to get result, As expected we should get balance in Destination address, but not able to get scheduled amount in destination address.

Kindly suggest.

**Comment by var500** [comment]
@vikas-speqto I also want to build and deploy this token-vesting program on devnet. Can you please help with the steps how this can be done? I am not sure how this needs to be done.

Thank you.

**Comment by syedshahzebhasnain** [comment]
Looking forward to this too

**Comment by dr497** [comment]
It's already deployed on devnet `Hj9R6bEfrULLNrApMsKCEaHR9QJ2JgRtM381xgYcjFmQ` (https://github.com/Bonfida/token-vesting/tree/master/js)

**Comment by DogLooksGood** [comment]
Is there an deployment on the mainnet that we can use directly?
